# Generated by Django 3.0.6 on 2020-06-05 14:10

from django.db import migrations
from django.contrib.auth import get_user_model

UserModel = get_user_model()


def create_super_user(*args, **options):
    print(f"\n  input with * is mandatory values...")
    email = "admin@webplatfom.com"
    name = "admin"
    password = "P@ssword124"

    try:
        UserModel.objects.get(email=email)
    except UserModel.DoesNotExist:
        user = UserModel.objects.create_user(email, password=password, name=name)
        user.is_superuser = True
        user.is_staff = True
        user.is_author = True
        user.save()
        # TODO - first login password change is not implemented.
        print(f"\n  {email} admin user is created with password '{password}'...\n  "
              "Please update your password on the first login...")
    else:
        print(f"User {email} already exists in the application")


def reverse_func(apps, schema_editor):
    UserModel.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_super_user, reverse_func),
    ]
